version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r CF_Template.zip InfraSetup/cf_linux_instance.yaml InfraSetup/test-stack-configuration.json
      - aws s3 cp CF_Template.zip s3://demo-4-codedeploy/
