AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template creates an Amazon EC2 instance.'
Parameters:
  MachineImage:
        Type: "AWS::EC2::Image::Id"
  InstanceProfile:
        Type: "String"  
  InstanceType:
    ConstraintDescription: must be a valid EC2 instance type.
    Default: t2.micro
    Description: WebServer EC2 instance type
    Type: String
  KeyName:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
  SubnetId:
        Type: "AWS::EC2::Subnet::Id"
  SecurityGroups:
        Type: "List<AWS::EC2::SecurityGroup::Id>"
  TagKey:
        Type: "String"
        Default: "Name"
  TagValue:
        Type: "String"
        Default: "codedeploy_demo_EC2"


Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref MachineImage      
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref SecurityGroups
      InstanceInitiatedShutdownBehavior: terminate
      Tags: 
        - Key: !Ref TagKey
          Value: !Ref TagValue
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            set -e

            yum update -y
            yum install -y ruby

            yum install wget 

            cd /home/ec2-user

            wget https://aws-codedeploy-${AWS::Region}.s3.amazonaws.com/latest/install

            chmod +x ./install
            ./install auto  
Outputs:
  PublicIP:
    Description: EC2 public IP
    Value: !GetAtt WebServer.PublicIp